set(_CATKIN_CURRENT_PACKAGE "iteshu_robot")
set(iteshu_robot_VERSION "0.0.0")
set(iteshu_robot_MAINTAINER "arturo <arturo@todo.todo>")
set(iteshu_robot_PACKAGE_FORMAT "1")
set(iteshu_robot_BUILD_DEPENDS "cv_bridge" "geometry_msgs" "message_generation" "move_base_msgs" "openni_launch" "roscpp" "roslib" "rospy" "std_msgs" "tf" "turtlebot_teleop")
set(iteshu_robot_BUILD_EXPORT_DEPENDS "cv_bridge" "geometry_msgs" "move_base_msgs" "openni_launch" "roscpp" "roslib" "rospy" "std_msgs" "tf" "turtlebot_teleop")
set(iteshu_robot_BUILDTOOL_DEPENDS "catkin")
set(iteshu_robot_BUILDTOOL_EXPORT_DEPENDS )
set(iteshu_robot_EXEC_DEPENDS "cv_bridge" "geometry_msgs" "move_base_msgs" "openni_launch" "roscpp" "roslib" "rospy" "std_msgs" "tf" "turtlebot_teleop")
set(iteshu_robot_RUN_DEPENDS "cv_bridge" "geometry_msgs" "move_base_msgs" "openni_launch" "roscpp" "roslib" "rospy" "std_msgs" "tf" "turtlebot_teleop")
set(iteshu_robot_TEST_DEPENDS )
set(iteshu_robot_DOC_DEPENDS )
set(iteshu_robot_DEPRECATED "")